//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Scripts/Capsule_COntrol.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Capsule_COntrol: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Capsule_COntrol()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Capsule_COntrol"",
    ""maps"": [
        {
            ""name"": ""Capsule_Controller"",
            ""id"": ""8d5c96d4-1093-4b1c-aa0f-ec0771a34ec2"",
            ""actions"": [
                {
                    ""name"": ""MoveXZ"",
                    ""type"": ""Value"",
                    ""id"": ""2ff4c783-c039-4ad3-ac9f-df0560cc065e"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MoveY"",
                    ""type"": ""Value"",
                    ""id"": ""6b450fe6-772a-4c08-b87c-5ffd0e079e9f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PauseActivate"",
                    ""type"": ""Button"",
                    ""id"": ""39187c22-dfe0-4068-ace8-6cfc08ad64ad"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""XR"",
                    ""id"": ""550c5da0-d62b-4f79-ba7d-72335663577f"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveXZ"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""6c4088c2-18ee-482d-a908-ee06ea172217"",
                    ""path"": ""<XRController>{LeftHand}/thumbstick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveXZ"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""efc30ea9-03ae-4433-bf9c-6ef5f9b39943"",
                    ""path"": ""<XRController>{LeftHand}/thumbstick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveXZ"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""302422de-030d-4612-bbf7-dba337f6c15c"",
                    ""path"": ""<XRController>{LeftHand}/thumbstick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveXZ"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""79c41479-c175-4937-80a5-038198446b54"",
                    ""path"": ""<XRController>{LeftHand}/thumbstick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveXZ"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Key"",
                    ""id"": ""7b28cc26-135f-479a-9fa0-dc015678dba6"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveXZ"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""574c3cc9-1dc7-4aee-b8a8-424a51854520"",
                    ""path"": ""<Keyboard>/#(W)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveXZ"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""5f408835-12e9-4e2a-baf9-8a518dcff336"",
                    ""path"": ""<Keyboard>/#(S)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveXZ"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""dc47648b-49b6-492b-bf01-3597b289de90"",
                    ""path"": ""<Keyboard>/#(A)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveXZ"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""ad829a11-c251-4fab-ae83-e1144993e9f5"",
                    ""path"": ""<Keyboard>/#(D)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveXZ"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""XR"",
                    ""id"": ""7d53ae91-aa30-4851-b687-a7b03a28e27a"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveY"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""5344552f-4fac-45f2-bbcb-8baf2d8959b8"",
                    ""path"": ""<XRController>{RightHand}/thumbstick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""9ee5d466-a292-4ba7-908c-945c782b185c"",
                    ""path"": ""<XRController>{RightHand}/thumbstick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""a86f2109-518f-447d-b537-9de30eb2d547"",
                    ""path"": ""<XRController>{RightHand}/thumbstick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""35fed94f-b890-41f0-9ca3-79d591ccc9eb"",
                    ""path"": ""<XRController>{RightHand}/thumbstick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Key"",
                    ""id"": ""6c0386c3-5b0e-4e7f-9fd8-b22a1762bc2c"",
                    ""path"": ""2DVector(mode=2)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveY"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""d860d308-fd73-4047-8eb9-c7306ff5ebb8"",
                    ""path"": ""<Keyboard>/#(Q)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""d56970a2-b8e5-4a02-be6f-666bcb7b08fc"",
                    ""path"": ""<Keyboard>/#(E)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveY"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""69c4fcfa-8e20-4e42-8b58-6e9ad5b955c7"",
                    ""path"": ""<XRController>{LeftHand}/{GripButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PauseActivate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6c394cee-6191-4bbb-b4fc-95f044f7a4db"",
                    ""path"": ""<XRController>{RightHand}/{GripButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PauseActivate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Capsule_Controller
        m_Capsule_Controller = asset.FindActionMap("Capsule_Controller", throwIfNotFound: true);
        m_Capsule_Controller_MoveXZ = m_Capsule_Controller.FindAction("MoveXZ", throwIfNotFound: true);
        m_Capsule_Controller_MoveY = m_Capsule_Controller.FindAction("MoveY", throwIfNotFound: true);
        m_Capsule_Controller_PauseActivate = m_Capsule_Controller.FindAction("PauseActivate", throwIfNotFound: true);
    }

    ~@Capsule_COntrol()
    {
        UnityEngine.Debug.Assert(!m_Capsule_Controller.enabled, "This will cause a leak and performance issues, Capsule_COntrol.Capsule_Controller.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Capsule_Controller
    private readonly InputActionMap m_Capsule_Controller;
    private List<ICapsule_ControllerActions> m_Capsule_ControllerActionsCallbackInterfaces = new List<ICapsule_ControllerActions>();
    private readonly InputAction m_Capsule_Controller_MoveXZ;
    private readonly InputAction m_Capsule_Controller_MoveY;
    private readonly InputAction m_Capsule_Controller_PauseActivate;
    public struct Capsule_ControllerActions
    {
        private @Capsule_COntrol m_Wrapper;
        public Capsule_ControllerActions(@Capsule_COntrol wrapper) { m_Wrapper = wrapper; }
        public InputAction @MoveXZ => m_Wrapper.m_Capsule_Controller_MoveXZ;
        public InputAction @MoveY => m_Wrapper.m_Capsule_Controller_MoveY;
        public InputAction @PauseActivate => m_Wrapper.m_Capsule_Controller_PauseActivate;
        public InputActionMap Get() { return m_Wrapper.m_Capsule_Controller; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Capsule_ControllerActions set) { return set.Get(); }
        public void AddCallbacks(ICapsule_ControllerActions instance)
        {
            if (instance == null || m_Wrapper.m_Capsule_ControllerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_Capsule_ControllerActionsCallbackInterfaces.Add(instance);
            @MoveXZ.started += instance.OnMoveXZ;
            @MoveXZ.performed += instance.OnMoveXZ;
            @MoveXZ.canceled += instance.OnMoveXZ;
            @MoveY.started += instance.OnMoveY;
            @MoveY.performed += instance.OnMoveY;
            @MoveY.canceled += instance.OnMoveY;
            @PauseActivate.started += instance.OnPauseActivate;
            @PauseActivate.performed += instance.OnPauseActivate;
            @PauseActivate.canceled += instance.OnPauseActivate;
        }

        private void UnregisterCallbacks(ICapsule_ControllerActions instance)
        {
            @MoveXZ.started -= instance.OnMoveXZ;
            @MoveXZ.performed -= instance.OnMoveXZ;
            @MoveXZ.canceled -= instance.OnMoveXZ;
            @MoveY.started -= instance.OnMoveY;
            @MoveY.performed -= instance.OnMoveY;
            @MoveY.canceled -= instance.OnMoveY;
            @PauseActivate.started -= instance.OnPauseActivate;
            @PauseActivate.performed -= instance.OnPauseActivate;
            @PauseActivate.canceled -= instance.OnPauseActivate;
        }

        public void RemoveCallbacks(ICapsule_ControllerActions instance)
        {
            if (m_Wrapper.m_Capsule_ControllerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICapsule_ControllerActions instance)
        {
            foreach (var item in m_Wrapper.m_Capsule_ControllerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_Capsule_ControllerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public Capsule_ControllerActions @Capsule_Controller => new Capsule_ControllerActions(this);
    public interface ICapsule_ControllerActions
    {
        void OnMoveXZ(InputAction.CallbackContext context);
        void OnMoveY(InputAction.CallbackContext context);
        void OnPauseActivate(InputAction.CallbackContext context);
    }
}
